version: '3.7'
services:
  dtexbe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dtex-fe
    image: dtex-fe
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dtex-fe

networks:
  dtex-fe:
    driver: bridge