# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: DTEX FE CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - run: |
        docker stop dtex-fe || true
        docker rm dtex-fe || true
        docker-compose -f docker-compose.yml up -d
        docker image prune -f
